import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import HeroSection from "@/components/HeroSection";
import SellingPointsSection from "@/components/SellingPointsSection";
import SolarCalculatorExplanation from "@/components/SolarCalculatorExplanation";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 min-h-screen flex flex-col`}
        >
        {/* NavBar stays on top */}
        <NavBar />

        {/* Main content expands to push footer down */}
        <main className="flex-grow container mx-auto p-4">
            {children}
        </main>

        {/* Footer stays at the bottom */}
        <Footer />
        </body>
        </html>
    );
}